version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cmgt_user
      - POSTGRES_PASSWORD=cmgt_password
      - POSTGRES_DB=cmgt_db